@DotnetApi_HostAddress = https://localhost:7208

GET {{DotnetApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DotnetApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###
